Styling + Updating HomePage
NeoCirc/neocirc-website pull request #42
Opened 2022-01-24 20:26 UTC by valistelea

I have finished creating the general backbone of the homepage. The background is a dynamic gradient background that peacefully changes colors and is incorporated using CSS. As the individual pages for the doctor and parent specific content are not created yet the buttons both link to the modules page, however this will be a very simple fix once the respective pages will be implemented. The biggest difficulty was the centering of the components as having them in the center was not good as once the menu on the left was expanded, it would go over the components, so I had to manually move the components to the right to prevent them from being covered up. Below, I have attached two images of the homepage and how it responds to the menu being expanded. 
<img width="1434" alt="Screen Shot 2022-01-24 at 3 21 19 PM" src="https://user-images.githubusercontent.com/23870844/150859175-c642c99c-ef8d-49e6-b21f-5e5cc0ea621e.png">
<img width="1431" alt="Screen Shot 2022-01-24 at 3 21 29 PM" src="https://user-images.githubusercontent.com/23870844/150859189-ca980a51-2457-4755-8b4a-270969178bbb.png">

2022-01-24 21:13 UTC, masakiasanuma commented
I love the background gradient, that's a nice touch

2022-01-24 21:26 UTC, masakiasanuma requested changes
Reviewed your code and left some comments

2022-01-24 21:26 UTC, masakiasanuma commented on src/components/HomePage.js
> +            }}>
So this works fine, but might be nice to wrap it in a styled-components component to keep it consistent

2022-01-24 21:26 UTC, masakiasanuma commented on src/components/HomePage.js
> +
```suggestion
    padding-left: 20px;
```
or whatever padding left necessary to account for the `&nbsp`

2022-01-24 21:26 UTC, masakiasanuma commented on src/components/HomePage.js
> +            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Instead of doing this &nbsp stuff, you can add `padding-left: 20px` or however much left padding in the `Wrap` component

2022-01-24 21:29 UTC, masakiasanuma requested changes
Can you add `.DS_Store` in `.gitignore`? I don't think it's a necessary file and it should be ignored.

2022-01-24 21:29 UTC, masakiasanuma requested changes
Can you also link the issue associated with this PR?

2022-01-24 23:51 UTC, masakiasanuma approved these changes

2022-01-25 00:03 UTC, SebastianWilson approved these changes

2022-01-25 14:10 UTC, merged